name: Create new release

on:
  push:
    tags:
      - '*'

jobs:
  test:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup GO environment
        uses: actions/setup-go@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: ./...
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}